<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="Search a PK model space from R with ferx: MFL search spaces, modelsearch, iivsearch, iovsearch, ruvsearch, covsearch, allometry, the globalsearch grid, and the ferx_amd() pipeline.">

<title>Example: Model search and automatic model development – ferx</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../assets/ferx-favicon.svg" rel="icon" type="image/svg+xml">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-51776f957f81c5a6b38322b65a6a6987.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-31632d092df9090a2ed68f79c078059d.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-51776f957f81c5a6b38322b65a6a6987.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-c732ebd5cd30270671b22a7aed1dc761.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-bce9ac5131b28a06f2bac66cf12fad62.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../site_libs/bootstrap/bootstrap-c732ebd5cd30270671b22a7aed1dc761.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../styles.css">
<meta property="og:title" content="Example: Model search and automatic model development – ferx">
<meta property="og:description" content="Open-source nonlinear mixed-effects modeling for population PK/PD, with an R package and high-performance Rust engine">
<meta property="og:site_name" content="ferx">
<meta property="og:locale" content="en_US">
<meta name="twitter:title" content="Example: Model search and automatic model development – ferx">
<meta name="twitter:description" content="Open-source nonlinear mixed-effects modeling for population PK/PD, with an R package and high-performance Rust engine">
<meta name="twitter:card" content="summary">
<link rel="canonical" href="https://ferx-nlme.org/examples/model-search.html">
</head>

<body class="nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../assets/ferx-dsl-brackets.svg" alt="ferx" class="navbar-logo light-content">
    <img src="../assets/ferx-dsl-brackets.svg" alt="ferx" class="navbar-logo dark-content">
    </a>
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">ferx</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../get-started.html"> 
<span class="menu-text">Get started</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../design.html"> 
<span class="menu-text">Design</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../features.html"> 
<span class="menu-text">Features</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../changelog.html"> 
<span class="menu-text">Changelog</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../roadmap.html"> 
<span class="menu-text">Roadmap</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../blog/index.html"> 
<span class="menu-text">Blog</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://ferx-nlme.github.io/ferx-core/"> 
<span class="menu-text">ferx-core</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://ferx-nlme.github.io/ferx-book/"> 
<span class="menu-text">ferx-r</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../reference/index.html"> 
<span class="menu-text">Reference</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/FeRx-NLME"> <i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#the-search-space-is-mfl" id="toc-the-search-space-is-mfl" class="nav-link active" data-scroll-target="#the-search-space-is-mfl">The search space is MFL</a></li>
  <li><a href="#check-the-space-before-paying-for-it" id="toc-check-the-space-before-paying-for-it" class="nav-link" data-scroll-target="#check-the-space-before-paying-for-it">Check the space before paying for it</a></li>
  <li><a href="#one-tool-at-a-time" id="toc-one-tool-at-a-time" class="nav-link" data-scroll-target="#one-tool-at-a-time">One tool at a time</a></li>
  <li><a href="#all-axes-at-once-ferx_globalsearch" id="toc-all-axes-at-once-ferx_globalsearch" class="nav-link" data-scroll-target="#all-axes-at-once-ferx_globalsearch">All axes at once: <code>ferx_globalsearch()</code></a>
  <ul class="collapse">
  <li><a href="#the-criterion-is-not-the-whole-of-the-ranking" id="toc-the-criterion-is-not-the-whole-of-the-ranking" class="nav-link" data-scroll-target="#the-criterion-is-not-the-whole-of-the-ranking">The criterion is not the whole of the ranking</a></li>
  <li><a href="#the-genetic-algorithm" id="toc-the-genetic-algorithm" class="nav-link" data-scroll-target="#the-genetic-algorithm">The genetic algorithm</a></li>
  </ul></li>
  <li><a href="#the-whole-pipeline-ferx_amd" id="toc-the-whole-pipeline-ferx_amd" class="nav-link" data-scroll-target="#the-whole-pipeline-ferx_amd">The whole pipeline: <code>ferx_amd()</code></a>
  <ul class="collapse">
  <li><a href="#plan-first" id="toc-plan-first" class="nav-link" data-scroll-target="#plan-first">Plan first</a></li>
  <li><a href="#then-run-it" id="toc-then-run-it" class="nav-link" data-scroll-target="#then-run-it">Then run it</a></li>
  <li><a href="#what-the-result-carries" id="toc-what-the-result-carries" class="nav-link" data-scroll-target="#what-the-result-carries">What the result carries</a></li>
  </ul></li>
  <li><a href="#reading-a-run-back" id="toc-reading-a-run-back" class="nav-link" data-scroll-target="#reading-a-run-back">Reading a run back</a></li>
  <li><a href="#notes" id="toc-notes" class="nav-link" data-scroll-target="#notes">Notes</a></li>
  <li><a href="#see-also" id="toc-see-also" class="nav-link" data-scroll-target="#see-also">See also</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/FeRx-NLME/ferx-r/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Example: Model search and automatic model development</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Model development is a sequence of decisions — one compartment or two, which parameters carry between-subject variability, whether the residual error needs a time-varying term, which covariates earn their place. ferx can make those decisions by search rather than by hand, using the same tool chain as Pharmpy’s <code>amd</code>, driven from R.</p>
<p>There are seven tools and one pipeline that runs six of them in order:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Function</th>
<th>Decides</th>
<th>Ranks on</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><a href="../reference/ferx_modelsearch.html"><code>ferx_modelsearch()</code></a></td>
<td>structural model — absorption, peripheral compartments, transits, lag time</td>
<td>BIC (mixed)</td>
</tr>
<tr class="even">
<td><a href="../reference/ferx_iivsearch.html"><code>ferx_iivsearch()</code></a></td>
<td>which parameters carry an eta, and which etas are correlated</td>
<td>BIC (IIV)</td>
</tr>
<tr class="odd">
<td><a href="../reference/ferx_iovsearch.html"><code>ferx_iovsearch()</code></a></td>
<td>which parameters carry inter-occasion variability</td>
<td>BIC (random)</td>
</tr>
<tr class="even">
<td><a href="../reference/ferx_ruvsearch.html"><code>ferx_ruvsearch()</code></a></td>
<td>the residual-error model</td>
<td>likelihood-ratio test</td>
</tr>
<tr class="odd">
<td><a href="../reference/ferx_covsearch.html"><code>ferx_covsearch()</code></a></td>
<td>which covariate effects to include (SCM, forward / forward-backward)</td>
<td>likelihood-ratio test</td>
</tr>
<tr class="even">
<td><a href="../reference/ferx_allometry.html"><code>ferx_allometry()</code></a></td>
<td>allometric scaling on weight — a transform, not a search</td>
<td>—</td>
</tr>
<tr class="odd">
<td><a href="../reference/ferx_globalsearch.html"><code>ferx_globalsearch()</code></a></td>
<td>structure <strong>and</strong> covariates together, as one grid — exhaustively or by genetic algorithm</td>
<td>penalized fitness</td>
</tr>
<tr class="even">
<td><a href="../reference/ferx_amd.html"><code>ferx_amd()</code></a></td>
<td>the six stepwise tools, in order, each step starting from what the last one selected</td>
<td>per step</td>
</tr>
</tbody>
</table>
<p>Everything below runs against bundled examples, so it is reproducible without your own data.</p>
<section id="the-search-space-is-mfl" class="level2">
<h2 class="anchored" data-anchor-id="the-search-space-is-mfl">The search space is MFL</h2>
<p>A space is written in Pharmpy’s <strong>Model Feature Language</strong>, quoted verbatim — ferx never translates R arguments into MFL, which is what makes a space portable between the two tools.</p>
<pre><code>ABSORPTION(FO); PERIPHERALS(0..1); LAGTIME([OFF,ON])
IIV?(@PK, exp); COVARIANCE?(IIV, *)</code></pre>
<p>A statement without <code>?</code> is <strong>structural</strong>: every candidate has it. A statement with <code>?</code> is <strong>exploratory</strong>: the search decides. <code>@PK</code>, <code>@IIV</code>, <code>@CONTINUOUS</code> and <code>@CATEGORICAL</code> are resolved against your model and your dataset, so one space travels across models.</p>
</section>
<section id="check-the-space-before-paying-for-it" class="level2">
<h2 class="anchored" data-anchor-id="check-the-space-before-paying-for-it">Check the space before paying for it</h2>
<p><code>ferx_search_config()</code> loads a <code>.ferxsearch</code> file through the engine’s own loader. An unknown section, an unparseable space, an empty space, an unrecognised <code>[rank] type</code> and a feature the engine cannot build are all errors <em>here</em>, before the first candidate is fitted.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ferx)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>ex  <span class="ot">&lt;-</span> <span class="fu">ferx_example</span>(<span class="st">"warfarin_amd"</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>cfg <span class="ot">&lt;-</span> <span class="fu">ferx_search_config</span>(ex<span class="sc">$</span>search)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>cfg</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>&lt;ferx search configuration&gt;
  file:  warfarin_amd.ferxsearch
  base:  .../examples/models/warfarin_amd.ferx
  data:  .../examples/data/warfarin.csv

Search space (5 features):
  mfl = ABSORPTION(FO); PERIPHERALS(0..1); LAGTIME([OFF,ON])
IIV?(@PK, exp); COVARIANCE?(IIV, *)

  ABSORPTION(FO)                                 (structural)
  PERIPHERALS(0..1)                              (structural)
  LAGTIME([OFF,ON])                              (structural)
  IIV?(@PK,EXP)                                  (exploratory)
  COVARIANCE?(IIV,*)                             (exploratory)

Rank: bic   cutoff: (tool default)
Strictness (* = set by the file):
  * require_converged      TRUE
    require_covariance     FALSE
    max_condition_number   1000
    max_correlation        0.95
    reject_on_boundary     TRUE
    reject_init_stall      TRUE
Run: threads = auto, retries = 1, resume = FALSE
Tool sections: amd, iivsearch, modelsearch, ruvsearch</code></pre>
<p>Two more functions make an interactive space debuggable. <code>ferx_search_space()</code> expands the <code>@</code>-symbols against a model and its data, so you can see what a one-line space actually means on <em>your</em> model:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ferx_search_space</span>(<span class="st">"COVARIATE?(@IIV, @CONTINUOUS, [pow, lin])"</span>,</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">model =</span> <span class="fu">ferx_example</span>(<span class="st">"two_cpt_oral_cov"</span>)<span class="sc">$</span>model,</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">data  =</span> <span class="fu">ferx_example</span>(<span class="st">"two_cpt_oral_cov"</span>)<span class="sc">$</span>data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>&lt;ferx search space&gt; (resolved against the base model)
  mfl = COVARIATE?(@IIV, @CONTINUOUS, [pow, lin])

                         feature   keyword optional
1    COVARIATE?(CL,WT,[pow,lin]) COVARIATE     TRUE
2  COVARIATE?(CL,CRCL,[pow,lin]) COVARIATE     TRUE
3    COVARIATE?(V1,WT,[pow,lin]) COVARIATE     TRUE
...
10 COVARIATE?(KA,CRCL,[pow,lin]) COVARIATE     TRUE

20 covariate effects (see attr(, "covariate_effects"))</code></pre>
<p>And <code>ferx_search_coverage()</code> reports a feature the engine cannot express as a row rather than as an aborted run:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ferx_search_coverage</span>(<span class="st">"ABSORPTION([FO, ZO, SEQ-ZO-FO]); ELIMINATION(FO)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>                feature covered  reason
1 ABSORPTION(SEQ-ZO-FO)   FALSE  sequential zero-order-then-first-order absorption is
                                 not one input term on a standard disposition but a
                                 depot of its own ... write it by hand and search
                                 around it
2       ELIMINATION(FO)    TRUE  &lt;NA&gt;</code></pre>
<p>The tools themselves refuse an uncovered feature outright — a search that quietly narrowed your space would answer a question you did not ask.</p>
</section>
<section id="one-tool-at-a-time" class="level2">
<h2 class="anchored" data-anchor-id="one-tool-at-a-time">One tool at a time</h2>
<p>Every tool takes <strong>either</strong> a <code>.ferxsearch</code> file <strong>or</strong> inline arguments, never a mix. The file is the reproducible artifact; the inline form is for a one-off.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>ex <span class="ot">&lt;-</span> <span class="fu">ferx_example</span>(<span class="st">"warfarin"</span>)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>res <span class="ot">&lt;-</span> <span class="fu">ferx_modelsearch</span>(</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">model        =</span> ex<span class="sc">$</span>model,</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">data         =</span> ex<span class="sc">$</span>data,</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">search_space =</span> <span class="st">"ABSORPTION(FO); PERIPHERALS(0..1); LAGTIME([OFF,ON])"</span>,</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">directory    =</span> <span class="st">"modelsearch-run"</span>,</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">progress     =</span> <span class="fu">interactive</span>()</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>res</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>ferx structural model search (reduced_stepwise, ranked on bic_mixed)
  Data:  .../examples/data/warfarin.csv
  Wrote: modelsearch-run
  Base:  base - FO, 0 peripherals
  bic_mixed:   -261.8 (base) -&gt; -261.8 (base)
  5 models over 2 layers

Ranked models (best first):
 rank   id              structure    ofv criterion d_criterion converged passed
    1 base      FO, 0 peripherals -280.4    -261.8       0.000      TRUE   TRUE
    2 run1 FO, 0 peripherals, lag -282.7    -259.6       2.258      TRUE   TRUE

3 models excluded by the strictness gate; summary() lists them.</code></pre>
<p>Two things in that output are the point of the whole family:</p>
<ul>
<li><p><strong>The base model won.</strong> A search that cannot answer “none of the above” is a search that always finds something.</p></li>
<li><p><strong>Three models were excluded, and they are still in the table.</strong> A candidate that failed to converge, hit a bound or came back ill-conditioned is not a result to be ranked. <code>summary(res)</code> prints each exclusion with the gate’s own words, and <code>res$models$passed</code> is a column you can filter on — never a silent drop:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>res<span class="sc">$</span>models[<span class="sc">!</span>res<span class="sc">$</span>models<span class="sc">$</span>passed, <span class="fu">c</span>(<span class="st">"id"</span>, <span class="st">"structure"</span>, <span class="st">"failures"</span>)]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>    id             structure
3 run2      FO, 1 peripheral
4 run3 FO, 1 peripheral, lag
5 run4 FO, 1 peripheral, lag
                                                                      failures
3 condition number 2.5654e5 exceeds 1.0000e3; parameter correlation |r| = 1.0000
  exceeds 0.9500 (TVKA ~ TVV2)
4 estimate pinned to a declared bound: TVQ
5 condition number 2.3613e5 exceeds 1.0000e3; parameter correlation |r| = 1.0000
  exceeds 0.9500 (TVKA ~ TVV2)</code></pre>
<p>Those three are the lowest-OFV models in the run. A winner-only view would have reported one of them.</p></li>
</ul>
<p>The other tools read the same way. <code>ferx_iivsearch()</code> decides the variability structure in two stages — which parameters keep an eta, then which of the survivors are correlated:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ferx_iivsearch</span>(<span class="at">model =</span> ex<span class="sc">$</span>model, <span class="at">data =</span> ex<span class="sc">$</span>data,</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>               <span class="at">search_space =</span> <span class="st">"IIV?(@PK, exp); COVARIANCE?(IIV, *)"</span>,</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">directory =</span> <span class="st">"iivsearch-run"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>ferx variability-structure search (top_down_exhaustive + block structure, ranked on bic_iiv)
  Input: [ETA_CL]+[ETA_KA]+[ETA_V]
  bic_iiv:   -273.5 (input) -&gt; -273.5 (input)
  12 models over 2 steps

Step 1 (no_of_etas), parent input ([ETA_CL]+[ETA_KA]+[ETA_V]):
 rank    id                 structure criterion d_criterion  best
    1 input [ETA_CL]+[ETA_KA]+[ETA_V]   -273.50         0.0  TRUE
    2  run1         [ETA_CL]+[ETA_KA]    -14.16      -259.3 FALSE
    3  run2          [ETA_CL]+[ETA_V]     85.01      -358.5 FALSE
    ...

Step 2 (block_structure), parent input ([ETA_CL]+[ETA_KA]+[ETA_V]):
 rank    id                 structure criterion d_criterion  best
    1 input [ETA_CL]+[ETA_KA]+[ETA_V]    -273.5      0.0000  TRUE
    2 run11     [ETA_CL,ETA_KA,ETA_V]    -269.5     -3.9550 FALSE
   NA  run8   [ETA_CL,ETA_KA]+[ETA_V]    -274.1      0.6501 FALSE
   ...

Selected variability structure (input):
  IIV:         ETA_CL, ETA_KA, ETA_V
  Correlated:  (none - every eta is diagonal)</code></pre>
<p>The etas are named, not numbered: a search over variability structure that reported <code>OMEGA(2,1)</code> would make you look the mapping up on every row. A block prints as <code>ETA_V ~ ETA_CL</code> and an IOV term as <code>KAPPA_CL</code>, with <code>OMEGA(i,j)</code> only where the model gave no name.</p>
<p><code>ferx_ruvsearch()</code> tests residual-error features by likelihood-ratio test, one iteration at a time, and reports the p-value it decided on:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ferx_ruvsearch</span>(<span class="at">model =</span> ex<span class="sc">$</span>model, <span class="at">data =</span> ex<span class="sc">$</span>data, <span class="at">directory =</span> <span class="st">"ruvsearch-run"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>ferx residual-error search (likelihood-ratio test at p = 0.001)
  OFV:   -280.364 (input) -&gt; -280.364 (input, dOFV 0.000)
  1 iteration, 6 models fitted

Candidates by iteration:
 iteration       feature       family    ofv       dofv p_value significant passed
         1         power        power -280.7  0.3016000  0.5829       FALSE  FALSE
         1      combined     combined -280.4 -0.0005840  1.0000       FALSE   TRUE
         1 time_varying1 time_varying -280.9  0.5605000  0.4540       FALSE   TRUE
         1 time_varying2 time_varying -281.0  0.5963000  0.4400       FALSE   TRUE
         1 time_varying3 time_varying -280.4  0.0002039  0.9886       FALSE  FALSE

Selected residual-error model:
  (none - the input model's error model was not improved on)
    DV ~ proportional(PROP_ERR)

Notes:
  - IIV_on_RUV not tested: [fit_options] method has no eta-eps interaction, and
    `iiv_on_ruv` needs one (focei, imp, impmap or saem)</code></pre>
<p>The remaining two need a model that declares its covariates, so they switch examples: <code>two_cpt_oral_base</code> is the covariate-free two-compartment oral model, and its <code>[covariates]</code> block is what makes <code>@CONTINUOUS</code> resolvable and <code>WT</code> available to scale on.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>cov_ex <span class="ot">&lt;-</span> <span class="fu">ferx_example</span>(<span class="st">"two_cpt_oral_base"</span>)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Stepwise covariate modelling (forward, then backward elimination)</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ferx_covsearch</span>(<span class="at">model =</span> cov_ex<span class="sc">$</span>model, <span class="at">data =</span> cov_ex<span class="sc">$</span>data,</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>               <span class="at">search_space =</span> <span class="st">"COVARIATE?(@IIV, @CONTINUOUS, [pow, lin])"</span>,</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>               <span class="at">p_forward =</span> <span class="fl">0.01</span>, <span class="at">p_backward =</span> <span class="fl">0.001</span>,</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>               <span class="at">directory =</span> <span class="st">"covsearch-run"</span>)</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Allometric scaling: a transform, so it can run without fitting at all.</span></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a><span class="co"># `parameters` is left at its default, which takes every clearance and volume</span></span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a><span class="co"># the `pk` template line binds.</span></span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a><span class="fu">ferx_allometry</span>(cov_ex<span class="sc">$</span>model, cov_ex<span class="sc">$</span>data, <span class="at">covariate =</span> <span class="st">"WT"</span>,</span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>               <span class="at">reference =</span> <span class="dv">70</span>, <span class="at">fit =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>ferx allometric scaling
  Data:  .../examples/data/two_cpt_oral_cov.csv
  Model: .../ferx-allometry-544f261810ae.ferx

Scaling on WT (reference 70):
  CL ~ WT power(center = 70, fix = 0.75)
  Q ~ WT power(center = 70, fix = 0.75)
  V1 ~ WT power(center = 70, fix = 1)
  V2 ~ WT power(center = 70, fix = 1)

Not fitted (`fit = FALSE`); the scaled model is in `$model`.</code></pre>
</section>
<section id="all-axes-at-once-ferx_globalsearch" class="level2">
<h2 class="anchored" data-anchor-id="all-axes-at-once-ferx_globalsearch">All axes at once: <code>ferx_globalsearch()</code></h2>
<p>Every stepwise search tool above keeps the other decision classes fixed. <code>ferx_modelsearch()</code> decides the structure with the covariate model fixed; <code>ferx_covsearch()</code> decides the covariates with the structure fixed. That is cheap, and it is blind to exactly one thing: an effect that only pays off once another decision has gone the other way. A clearance covariate that earns its place only after the distribution phase has a compartment of its own is invisible to a forward step taken on the one-compartment model.</p>
<p><a href="../reference/ferx_globalsearch.html"><code>ferx_globalsearch()</code></a> lays both kinds of decision out as <strong>one grid</strong> and searches it whole. Every structural category in the space becomes an axis with its values as alleles; every optional <code>COVARIATE?</code> pair becomes an axis whose alleles are <code>none</code> and each of its forms. <code>algorithm = "exhaustive"</code> fits every point of the grid; <code>algorithm = "ga"</code> — the default — runs pyDarwin’s genetic algorithm over it and fits a fraction of them.</p>
<p>The bundled <code>two_cpt_oral_global</code> example is built to have something to find: a <em>one</em>-compartment, covariate-free model on data that carry <code>WT</code> and <code>CRCL</code> and were simulated from two compartments, so all four axes are live.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>ex  <span class="ot">&lt;-</span> <span class="fu">ferx_example</span>(<span class="st">"two_cpt_oral_global"</span>)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>res <span class="ot">&lt;-</span> <span class="fu">ferx_globalsearch</span>(<span class="at">config =</span> ex<span class="sc">$</span>search, <span class="at">directory =</span> <span class="st">"globalsearch-run"</span>)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>res</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>ferx global model search (exhaustive, ranked on penalized)
  Data:  .../examples/data/two_cpt_oral_cov.csv
  Wrote: globalsearch-run
  Grid:  16 points over 4 axes
    LAGTIME: OFF | ON
    PERIPHERALS: 0 | 1
    CL-WT: none | power
    CL-CRCL: none | power
  Input: OFV -172.2, penalized -102.2
  Fitness: -102.2 (input) -&gt; -796 (run6)
  17 models fitted of 17 evaluated

Ranked models (best first):
 rank    id                                              genome    ofv criterion fitness converged passed
    1  run6  LAGTIME=OFF;PERIPHERALS=1;CL-WT=none;CL-CRCL=power -896.0   -796.00 -796.00      TRUE   TRUE
    2  run8 LAGTIME=OFF;PERIPHERALS=1;CL-WT=power;CL-CRCL=power -901.3   -791.30 -791.30      TRUE   TRUE
    3 run13    LAGTIME=ON;PERIPHERALS=1;CL-WT=none;CL-CRCL=none -887.5   -777.50 -777.50      TRUE   TRUE
    4 run14   LAGTIME=ON;PERIPHERALS=1;CL-WT=none;CL-CRCL=power -895.4   -775.40 -775.40      TRUE   TRUE
    5 run15   LAGTIME=ON;PERIPHERALS=1;CL-WT=power;CL-CRCL=none -893.4   -773.40 -773.40      TRUE   TRUE
    6 run16  LAGTIME=ON;PERIPHERALS=1;CL-WT=power;CL-CRCL=power -896.4   -766.40 -766.40      TRUE   TRUE
    7  run1   LAGTIME=OFF;PERIPHERALS=0;CL-WT=none;CL-CRCL=none -172.2   -102.20 -102.20      TRUE   TRUE
    8 input                                                &lt;NA&gt; -172.2   -102.20 -102.20      TRUE   TRUE
    9  run2  LAGTIME=OFF;PERIPHERALS=0;CL-WT=none;CL-CRCL=power -179.4    -99.36  -99.36      TRUE   TRUE
   10  run3  LAGTIME=OFF;PERIPHERALS=0;CL-WT=power;CL-CRCL=none -179.3    -99.27  -99.27      TRUE   TRUE
   11  run4 LAGTIME=OFF;PERIPHERALS=0;CL-WT=power;CL-CRCL=power -185.5    -95.49  -95.49      TRUE   TRUE</code></pre>
<p><strong>Read the first two rows before anything else.</strong> <code>run8</code> has the better OFV (-901.3 against -896.0) and ranks <em>second</em>. It carries one more covariate relation than <code>run6</code>, and the penalized criterion charges it for the extra parameter. A table that showed only the OFV would name the wrong winner — which is the reason the criterion and the OFV are separate columns.</p>
<section id="the-criterion-is-not-the-whole-of-the-ranking" class="level3">
<h3 class="anchored" data-anchor-id="the-criterion-is-not-the-whole-of-the-ranking">The criterion is not the whole of the ranking</h3>
<p><code>[rank] type</code> defaults to <code>"penalized"</code> here, where every other tool defaults to a BIC: pyDarwin’s fitness, the objective function plus a charge per estimated parameter and per unhealthy fit. Whatever criterion you name, the global search then charges three further things the criterion cannot see, and ranks on the sum — the <code>fitness</code> column, always finite:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>charge</th>
<th>paid by</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>charge_non_influential</code></td>
<td>a gene that changed nothing in the rendered model — a covariate on a parameter the structural choice removed. A tie-break towards the simpler genotype among models that are otherwise identical.</td>
</tr>
<tr class="even">
<td><code>charge_gate</code></td>
<td>a fit the <code>[strictness]</code> gate refused. It can never be selected, but it still steers the genetic algorithm away from the region that produced it.</td>
</tr>
<tr class="odd">
<td><code>charge_crash</code></td>
<td>a candidate that produced no fit at all — it does not compile, or the fit errored. Large, and finite, so the algorithm can still rank it.</td>
</tr>
</tbody>
</table>
<p>They are columns of <code>$models</code>, beside the <code>criterion</code> and the <code>fitness</code> they add up to. <code>print()</code> lists the models that paid one:</p>
<pre><code>Models the search charged beyond the criterion:
    id                                             genome criterion charge_non_influential charge_gate charge_crash fitness
  run5  LAGTIME=OFF;PERIPHERALS=1;CL-WT=none;CL-CRCL=none   -411.00                      0         100            0  -311.0
  run7 LAGTIME=OFF;PERIPHERALS=1;CL-WT=power;CL-CRCL=none   -404.20                      0         100            0  -304.2
  run9   LAGTIME=ON;PERIPHERALS=0;CL-WT=none;CL-CRCL=none     16.52                      0         100            0   116.5
 run10  LAGTIME=ON;PERIPHERALS=0;CL-WT=none;CL-CRCL=power     19.34                      0         100            0   119.3
 run11  LAGTIME=ON;PERIPHERALS=0;CL-WT=power;CL-CRCL=none     19.46                      0         100            0   119.5
 run12  LAGTIME=ON;PERIPHERALS=0;CL-WT=power;CL-CRCL=power     23.34                      0         100            0   123.3</code></pre>
<p>This is the same “never a silent drop” rule the stepwise tools follow, one level further: a gated genome is not merely present in the table, it says what the gate cost it. Without that column, <code>run5</code> at fitness -311.0 would look like a model that simply fitted worse than <code>run6</code> — rather than one the gate refused, which happens to sit 100 units away because of it.</p>
<p><code>$penalties</code> is the effective schedule the run charged, so the fitness column can be read against the numbers that built it.</p>
</section>
<section id="the-genetic-algorithm" class="level3">
<h3 class="anchored" data-anchor-id="the-genetic-algorithm">The genetic algorithm</h3>
<p>Sixteen points is small enough to enumerate, which makes the exhaustive result a reference for the GA. With the settings and seed below, the GA finds the same winner. On a grid of thousands — six binary optional covariate pairs alone already give 64 covariate combinations — enumerating is not an option and finding a strong candidate at all is the point.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>res_ga <span class="ot">&lt;-</span> <span class="fu">ferx_globalsearch</span>(</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">model        =</span> ex<span class="sc">$</span>model,</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data         =</span> ex<span class="sc">$</span>data,</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">search_space =</span> <span class="fu">c</span>(<span class="st">"PERIPHERALS(0..1); LAGTIME([OFF,ON])"</span>,</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>                   <span class="st">"COVARIATE?(CL, WT, pow); COVARIATE?(CL, CRCL, pow)"</span>),</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">algorithm    =</span> <span class="st">"ga"</span>,</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">ga           =</span> <span class="fu">list</span>(<span class="at">population_size =</span> <span class="dv">8</span>, <span class="at">generations =</span> <span class="dv">3</span>, <span class="at">seed =</span> <span class="dv">20250914</span>),</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">directory    =</span> <span class="st">"globalsearch-ga"</span></span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>res_ga<span class="sc">$</span>generations</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>  index best best_fitness mean_fitness polished
1     0 run1    -779.4346    -323.4043        0
2     1 run9    -796.0057    -438.3091        0
3     2 run9    -796.0057    -441.3968        0
4     3 run9    -796.0057    -497.5284        1</code></pre>
<p><code>ga</code> takes a named list validated against the engine’s own key list, so a mistyped knob is refused by name before anything is fitted. The <code>seed</code> is what makes <code>resume = TRUE</code> reuse a journal: the same seed on the same grid proposes the same genomes.</p>
<p><code>algorithm</code> is matched exactly rather than by prefix — <code>algorithm = "e"</code> is an error naming the value, not a silent choice to enumerate a grid nobody has sized. For the same reason an exhaustive grid above <code>[globalsearch] max_models</code> (500 by default) is an error naming the size, never a truncated search.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Not the same as <code>ferx_fit(settings = list(global_search = TRUE))</code>
</div>
</div>
<div class="callout-body-container callout-body">
<p>That setting is a global <em>optimizer</em> phase inside the estimation of <strong>one</strong> model — a wider search for the parameter values of a fixed model. <code>ferx_globalsearch()</code> is a global search over <strong>models</strong>. The name here is the engine’s, the <code>.ferxsearch</code> file’s (<code>[globalsearch]</code>), the <code>ferx globalsearch</code> command’s and Pharmpy/pyDarwin’s, so a search stays portable between them.</p>
</div>
</div>
</section>
</section>
<section id="the-whole-pipeline-ferx_amd" class="level2">
<h2 class="anchored" data-anchor-id="the-whole-pipeline-ferx_amd">The whole pipeline: <code>ferx_amd()</code></h2>
<p><code>ferx_amd()</code> runs the tools in order, each step starting from the model the previous step selected. One space describes the whole pipeline; the engine partitions it by statement kind and hands each step only the statements its tool can read.</p>
<section id="plan-first" class="level3">
<h3 class="anchored" data-anchor-id="plan-first">Plan first</h3>
<p><code>ferx_amd_plan()</code> answers “what would run, and what would not” without fitting anything:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>ex <span class="ot">&lt;-</span> <span class="fu">ferx_example</span>(<span class="st">"warfarin_amd"</span>)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ferx_amd_plan</span>(<span class="at">config =</span> ex<span class="sc">$</span>search)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>  index       step        tool rerun      directory
1     1 structural modelsearch FALSE 01-modelsearch
2     2  iivsearch   iivsearch FALSE   02-iivsearch
3     3   residual   ruvsearch FALSE   03-ruvsearch
4     4  iovsearch   iovsearch FALSE   04-iovsearch
5     5  allometry   allometry FALSE   05-allometry
6     6 covariates   covsearch FALSE   06-covsearch
                                                                        skipped
1                                                                          &lt;NA&gt;
2                                                                          &lt;NA&gt;
3                                                                          &lt;NA&gt;
4 the starting model declares no `iov_column` in [fit_options], so the dataset's
                                                     occasions were not read
5                                   the search space has no ALLOMETRY statement
6                                   the search space has no COVARIATE statement</code></pre>
<p>A step is skipped for a reason you can read, not because it silently found nothing to do.</p>
</section>
<section id="then-run-it" class="level3">
<h3 class="anchored" data-anchor-id="then-run-it">Then run it</h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>res <span class="ot">&lt;-</span> <span class="fu">ferx_amd</span>(<span class="at">config =</span> ex<span class="sc">$</span>search, <span class="at">directory =</span> <span class="st">"amd-run"</span>,</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">progress =</span> <span class="fu">interactive</span>())</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>res</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>ferx AMD pipeline (default strategy, retries all_final)
  Model: .../examples/models/warfarin_amd.ferx
  Data:  .../examples/data/warfarin.csv
  Wrote: amd-run
  OFV:   -286.004 (start) -&gt; -286.004 (final, dOFV 0.000)
  3 of 6 steps ran, 28 models fitted, 8.8 s across the steps

Pipeline:
 index       step  status criterion value_before value_after    d_value
     1 structural     ran bic_mixed       -267.5      -267.5 -4.865e-10
     2  iivsearch     ran   bic_iiv       -279.1      -279.1  1.021e-09
     3   residual     ran       ofv       -286.0      -286.0 -4.380e-10
     4  iovsearch skipped      &lt;NA&gt;           NA          NA         NA
     5  allometry skipped      &lt;NA&gt;           NA          NA         NA
     6 covariates skipped      &lt;NA&gt;           NA          NA         NA
      d_ofv candidates converged passed seconds
 -4.865e-10          5      TRUE   TRUE  0.6229
  1.021e-09         12      TRUE   TRUE  0.6219
 -4.380e-10          7        NA     NA  7.5060
         NA          0        NA     NA  0.0000
         NA          0        NA     NA  0.0000
         NA          0        NA     NA  0.0000

Steps that did not run:
  4 iovsearch    skipped: the starting model declares no `iov_column` in [fit_options], so the dataset's occasions were not read
  5 allometry    skipped: the search space has no ALLOMETRY statement
  6 covariates   skipped: the search space has no COVARIATE statement

Selected:
  structural   FO, 0 peripherals
  iivsearch    [CL]+[KA]+[V]
  residual     no residual-error feature added

3 candidates excluded by the strictness gate; summary() lists them.</code></pre>
<p>The strategy decides the order: <code>default</code> is structural → IIV → residual → IOV → allometry → covariates; <code>reevaluation</code> appends a second IIV and residual pass once the model has its covariates; <code>SIR</code>, <code>SRI</code> and <code>RSI</code> run three steps in the order their initials spell.</p>
</section>
<section id="what-the-result-carries" class="level3">
<h3 class="anchored" data-anchor-id="what-the-result-carries">What the result carries</h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># One row per planned step, skipped ones included</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>res<span class="sc">$</span>steps[, <span class="fu">c</span>(<span class="st">"index"</span>, <span class="st">"step"</span>, <span class="st">"status"</span>, <span class="st">"criterion"</span>, <span class="st">"d_value"</span>,</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>              <span class="st">"converged"</span>, <span class="st">"passed"</span>, <span class="st">"selected"</span>)]</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Every candidate of every step, with the tool that produced it</span></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(res<span class="sc">$</span>candidates[, <span class="fu">c</span>(<span class="st">"step"</span>, <span class="st">"tool"</span>, <span class="st">"id"</span>, <span class="st">"description"</span>, <span class="st">"criterion"</span>,</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"value"</span>, <span class="st">"rank"</span>, <span class="st">"passed"</span>, <span class="st">"selected"</span>)])</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Candidates the gate excluded, in the gate's own words</span></span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>res<span class="sc">$</span>candidates[<span class="sc">!</span>res<span class="sc">$</span>candidates<span class="sc">$</span>passed, <span class="fu">c</span>(<span class="st">"step"</span>, <span class="st">"tool"</span>, <span class="st">"id"</span>, <span class="st">"failures"</span>)]</span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Each step's own result object, keyed by its directory</span></span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(res<span class="sc">$</span>tools)</span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] "01-structural" "02-iivsearch"  "03-residual"</span></span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a><span class="co"># The model the pipeline ended on: a fitted model, seeded with its own estimates</span></span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a>res<span class="sc">$</span>fit</span>
<span id="cb27-18"><a href="#cb27-18" aria-hidden="true" tabindex="-1"></a>res<span class="sc">$</span>final_model_path</span>
<span id="cb27-19"><a href="#cb27-19" aria-hidden="true" tabindex="-1"></a>res<span class="sc">$</span>d_ofv                  <span class="co"># final - start; negative is an improvement</span></span>
<span id="cb27-20"><a href="#cb27-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-21"><a href="#cb27-21" aria-hidden="true" tabindex="-1"></a><span class="co"># The engine's own report, as `ferx amd` prints it</span></span>
<span id="cb27-22"><a href="#cb27-22" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(res<span class="sc">$</span>summary_text)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>One trap worth naming: <code>criterion</code> says what <code>value</code> is on, and it is not always the step’s own scale. A ruvsearch candidate is fitted to its parent’s CWRES, so its number must not be compared with a data OFV. The column is there so you do not have to remember that.</p>
</section>
</section>
<section id="reading-a-run-back" class="level2">
<h2 class="anchored" data-anchor-id="reading-a-run-back">Reading a run back</h2>
<p>Every tool writes its run to <code>directory</code>, and the tables are the same ones the R object carries — so an interrupted run, or one driven from the <code>ferx</code> command-line tool, reads back the same way:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ferx_search_results</span>(<span class="st">"modelsearch-run"</span>, <span class="at">type =</span> <span class="st">"models"</span>)     <span class="co"># models.csv</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ferx_search_results</span>(<span class="st">"covsearch-run"</span>,   <span class="at">type =</span> <span class="st">"steps"</span>)      <span class="co"># steps.csv</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ferx_search_results</span>(<span class="st">"modelsearch-run"</span>)                      <span class="co"># candidates.csv</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Columns come from the engine’s own column list, typed on the way in: logicals are logical, an empty cell is <code>NA</code> rather than <code>NaN</code>. A partial run (<code>*.partial.csv</code>, written when a search is cancelled) reads back too.</p>
<p><code>resume = TRUE</code> picks a run up where it stopped, using the journal in <code>directory</code>; <code>threads</code> and <code>retries</code> mirror <a href="../reference/ferx_bootstrap.html"><code>ferx_bootstrap()</code></a>, the closest existing tool.</p>
</section>
<section id="notes" class="level2">
<h2 class="anchored" data-anchor-id="notes">Notes</h2>
<ul>
<li><strong>Some <code>.ferxsearch</code> sections have no R tool.</strong> The engine accepts a section for every tool <em>it</em> knows, which is more than this package binds — <code>[structsearch]</code> today. Such a file loads, and ferx warns that no R tool consumes the section, because the tool it <em>is</em> handed would otherwise run a different search without saying so. <code>[structsearch]</code> is accepted vocabulary with no engine module behind it yet, so it is reported without a remediation rather than with one that names a command that does not exist. What the warning reports is the complement of the sections this package has a tool for, so a section a later ferx-core adds is named from the day a file can carry it — and stops being named on the day a binding lands, as <code>[globalsearch]</code> did when <code>ferx_globalsearch()</code> shipped.</li>
<li><strong>Cancelling</strong> a search from R interrupts it at the next candidate boundary; the run still writes its partial tables.</li>
<li><strong>The strictness gate is shared.</strong> <code>[strictness]</code> in the configuration applies to every tool, and every table with one row per fitted model carries <code>converged</code> and <code>passed</code> columns — <code>$models</code> for modelsearch, iivsearch and iovsearch, <code>$steps</code> for covsearch and ruvsearch, <code>$comparison</code> for allometry. (The per-stage ranking <code>$steps</code> of iivsearch and iovsearch, and allometry’s <code>$scalings</code>, are not model tables and carry no gate columns; the models they rank are in <code>$models</code>.) Inside an AMD step the init-stall gate is turned off by design: each step starts from a model already at its own optimum, where “did not move from the initial estimates” is the expected outcome.</li>
</ul>
</section>
<section id="see-also" class="level2">
<h2 class="anchored" data-anchor-id="see-also">See also</h2>
<ul>
<li><a href="../reference/ferx_amd.html"><code>ferx_amd()</code></a>, <a href="../reference/ferx_amd_plan.html"><code>ferx_amd_plan()</code></a></li>
<li><a href="../reference/ferx_globalsearch.html"><code>ferx_globalsearch()</code></a> — the grid over structure and covariates together</li>
<li><a href="../reference/ferx_search_config.html"><code>ferx_search_config()</code></a>, <a href="../reference/ferx_search_space.html"><code>ferx_search_space()</code></a>, <a href="../reference/ferx_search_coverage.html"><code>ferx_search_coverage()</code></a>, <a href="../reference/ferx_search_results.html"><code>ferx_search_results()</code></a></li>
<li><a href="../reference/ferx_bic.html"><code>ferx_bic()</code></a> — the BIC variants the searches rank on</li>
<li><a href="../examples/covariates.html">Example: Covariate models</a> — writing a covariate effect by hand</li>
<li><a href="../examples/multistart.html">Example: Multi-start fitting</a> — robustness of a single fit, which is what a search assumes of its candidates</li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/ferx-nlme\.org");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2026 FeRx-NLME · MIT licensed</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/FeRx-NLME/ferx-r/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>Fe · 26 · Rx · 2026</p>
</div>
  </div>
</footer>




</body></html>